volumes:
  hermes:
  home:
services:
    hermes-agent:
        container_name: hermes
        restart: unless-stopped
        volumes:
            - home:/root
            - hermes:/opt/data
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - 8642
            - 9119
        build: .
        env_file:
          - .env
        command: gateway run
        environment:
          - HERMES_DASHBOARD=1
          - TELEGRAM_ALLOWED_USERS=282184670


